language: java
jdk:
  - oraclejdk8
env:
    global:
        - PROJECT_REPOSITORY="albertlatacz/java-repl"
        - PROJECT_VERSION=$TRAVIS_BUILD_NUMBER
        - secure: "GgktdD6R+usYtITrqJcpcgU0MjwZXI0kcL1MVwqJVH7+6dAxt2i4ddHj62lT2zjPah1EqL/OXVw3WrhI3kDgljSuG4kcFsTj/ZBDpzhFtFL6aF5SR49tHUykL5nSaIp53TVnHFnk5CuRUUVxAnlUxNLWDCNyYfD3GB2vxJnicMs="
        - secure: "bIFU+VgbcIJ5DmsXkoxTaLGI40uIyWdTFnco7FaJLoJLwLJSake4jemFv5SI\nJaSFVINBXA+Xn/qqHmFfWVr2fKsAevwRfkkIuTM1QMlN2TOMkCwOrz6mYA3f\nxjh+oKXUzNutZTHSyoCyZ72uHSJ33TlPWHU+OToS4AYxf8LrTYI="
        - secure: "O0xTkW+WBNWT0a44u7XRpm0vp0q04ZFv/ovmPX6nm3fRokuiHMoRaL1l7r1K\nLF9ow3n+Ncsl64XRJNv2rjKVrxb19GtZQjxnHqi6bW2FSnoTEJsfvIjgMOwh\nrOHL9MUP61idRqN15ki0qYsmZ8t3xN9rw04fJLGZn73Oy0uRSGI="
        - secure: "C5j0sZWXhfOoaVYyylyM7aJsjUSBbiIkW2GpAhODIrp/E5l297TymomFOCOTZSL1xF5V4RYt6jc7db+Qri5ryeHd0IIYMNWqcmni4rChtKp4b2F4qh+eqwre8RW5hONOcByZTQDvo+m3SCTuoTWcIM/UIhQIGovSPtYmqjQlSwI="
        - secure: "fpuaeSvHiDRtUGHRuCkaZOglaE8IujaCXjSShYP78kxaZUOkHCY6meGmk2YRB6nKTs80lpiQCGFOmtcdEOsCRt2kQXuzJR6NkcG8JEYbdD36G0zR/GpeZ38o3lZqd7Xy1FEGwTgMi0Wy699ZvSoBP1xtGz8A7f8G9ROV7E81gdw="
        - secure: "bxZ+/YMNG5guSA4R62wsIODwvslnqh4YwzaZjCuSO8FsXzEFkRLbZlgNTJYthcKEOZK0Oq+7d0nr0Dh2hKSgOx/FM2nCNzL3kMc/D4gAi54OET8wOv21PgiZQomPlZd5v62uTdw8XDrSzdEG8tzjrA21GDGNFF+Uuz3KPfoQfc0="
        - secure: "KdWNLW5VYhvGUMIB0Q4OwPfPAFLhVNi9hLRw2ZapBq245iVf7ayMXZznyOpSYgOjuXRqx/24ww+LSBFGM/rFetIiP2mA1A4RpxYpyRzJmfhxz3e4Rj71bE1JrLynY/MLIuH4NERMRdH1kZjQaY+IFkXqas5C+FD8Msj0owzlwLE="
        - secure: "Z5wmAFWOUv1fV3A/iCDrz9J59vZVzAn1tQigpYKdCTsvuZMHvk7SP3+3Aak2NEtuRzzu09WuBmCE6pfES3HbvD2W0jR2iqiv0bECnt5pCptC9QjlAw9vvGhm0Tz/aR4dJwzAjWBREU4LTgjN65416jclKV1HxhJcw90CZbYBmNo="
        - secure: "fovLGO44v27+u6dYAtT9zqpm/pJImgl6Bb4YqJ6VGSqx87axro3bkoeqlrw8aTThCqNxBCtoOPx7iPmQVi2l8fB5Dh7G8P50CYtT6fb9p8e7GHh9vZDBRk/UQmm5XALBX2dna1dN/UOKTyN/NFAajfCt6lAah5d9HvDpqw9E7Xs="
        - secure: "BhPDDFZqVLPx5g2Tu4n2AMT9MhmnFKmK9g+D+jmOkkn9CEMPByWoJDqOZghUE/1Dw0f8wv6wmjK6WfolmxT0lTTmybN9+b/K9yTULldx1tIQ+bXToaf+cSjw+ZBkY8WSgBa5h3tHSRLpjp+zgERuJR1erWsIpU6UDVfx2RgVHeg="
        - secure: "AZAE6aWnJyQvNsEL/9PFweOyVNnUxgWhdPHD4OONHr3y3D+uT7kZn6GJx0C0f4bvQGCX5ENGbDqh/NSEplD+85kwQrhW9Qi3G+zZbrENHygQUVaHi6OC+JmsIvkLS6WFe013jGAJeP3+dt8aE+VRIECtA7RvpHGS+ONCUh7YBVs="

sudo: required

branches:
    only:
        - master

services:
  - docker

script:
  - gradle clean check shadowJar bintrayUpload githubRelease

after_success:
    - sh bin/push-to-docker-hub.sh